const imageFiles = [
  {
    name: "ace of clubs",
    alt: "ace of clubs",
    url: "https://i.imgur.com/EqoVMIh.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "ace of hearts",
    alt: "ace of hearts",
    url: "https://i.imgur.com/szQofwg.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "ace of spades",
    alt: "ace of spades", 
    url: "https://i.imgur.com/mzcy0Xl.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "king of clubs",
    alt: "king of clubs",
    url: "https://i.imgur.com/YwHz9XC.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "queen of clubs",
    alt: "queen of clubs",
    url: "https://i.imgur.com/fyQCBEG.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "queen of diamonds",
    alt: "queen of diamonds",
    url: "https://i.imgur.com/2I2UPqI.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "seven of diamonds",
    alt: "seven of diamonds",
    url: "https://i.imgur.com/hBtEfon.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "jack of diamonds",
    alt: "jack of diamonds",
    url: "https://i.imgur.com/rNwkffE.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
  },
  {
    name: "ace of clubs 2",
    alt: "ace of clubs",
    url: "https://i.imgur.com/EqoVMIh.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "ace of hearts 2",
    alt: "ace of hearts",
    url: "https://i.imgur.com/szQofwg.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "ace of spades 2",
    alt: "ace of spades", 
    url: "https://i.imgur.com/mzcy0Xl.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "king of clubs 2",
    alt: "king of clubs",
    url: "https://i.imgur.com/YwHz9XC.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "queen of clubs 2",
    alt: "queen of clubs",
    url: "https://i.imgur.com/fyQCBEG.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "queen of diamonds 2",
    alt: "queen of diamonds",
    url: "https://i.imgur.com/2I2UPqI.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "seven of diamonds 2",
    alt: "seven of diamonds",
    url: "https://i.imgur.com/hBtEfon.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    name: "jack of diamonds 2",
    alt: "jack of diamonds",
    url: "https://i.imgur.com/rNwkffE.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
];

export default imageFiles;
