const imageFiles = [
  {
    id: "ace of clubs",
    match: "A",
    url: "https://i.imgur.com/EqoVMIh.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "ace of hearts",
    match: "B",
    url: "https://i.imgur.com/szQofwg.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "ace of spades",
    match: "C",
    url: "https://i.imgur.com/mzcy0Xl.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "king of clubs",
    match: "D",
    url: "https://i.imgur.com/YwHz9XC.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "queen of clubs",
    match: "E",
    url: "https://i.imgur.com/fyQCBEG.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "queen of diamonds",
    match: "F",
    url: "https://i.imgur.com/2I2UPqI.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "seven of diamonds",
    match: "G",
    url: "https://i.imgur.com/hBtEfon.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "jack of diamonds",
    match: "H",
    url: "https://i.imgur.com/rNwkffE.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
  },
  {
    id: "ace of clubs 2",
    match: "A",
    url: "https://i.imgur.com/EqoVMIh.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "ace of hearts 2",
    match: "B",
    url: "https://i.imgur.com/szQofwg.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "ace of spades 2",
    match: "C",
    url: "https://i.imgur.com/mzcy0Xl.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "king of clubs 2",
    match: "D",
    url: "https://i.imgur.com/YwHz9XC.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "queen of clubs 2",
    match: "E",
    url: "https://i.imgur.com/fyQCBEG.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "queen of diamonds 2",
    match: "F",
    url: "https://i.imgur.com/2I2UPqI.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "seven of diamonds 2",
    match: "G",
    url: "https://i.imgur.com/hBtEfon.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
  {
    id: "jack of diamonds 2",
    match: "H",
    url: "https://i.imgur.com/rNwkffE.png",
    back: "https://i.imgur.com/w1y1Ngz.png", 
    flipped: false,
    answered: false,
  },
];

export default imageFiles;
